export interface LocationItem {
  id: string;
  name: string;
  locality?: string;
  city: string;
  district?: string;
  state: string;
  country: string;
  type: "locality" | "city" | "airport" | "transit" | "tourist" | "landmark";
  aliases?: string[];
  lat?: number;
  lng?: number;
}

export const SOUTH_INDIA_LOCATIONS: LocationItem[] = [
  // ── BANGALORE LOCALITIES ──
  {
    id: "blr-rajajinagar",
    name: "Rajajinagar",
    locality: "Rajajinagar",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["rajaj", "raj", "rajaji nagar", "rajajinagar 1st block", "rajajinagar entrance", "isckon rajajinagar"],
    lat: 12.9982,
    lng: 77.553,
  },
  {
    id: "blr-rajarajeshwari-nagar",
    name: "Rajarajeshwari Nagar",
    locality: "RR Nagar",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["raj", "rr nagar", "rajarajeshwari", "mysore road rr nagar"],
    lat: 12.9255,
    lng: 77.5167,
  },
  {
    id: "blr-rajajinagar-metro",
    name: "Rajajinagar Metro Station",
    locality: "Rajajinagar",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "transit",
    aliases: ["rajaj metro", "rajajinagar green line", "metro rajajinagar"],
    lat: 12.9988,
    lng: 77.5532,
  },
  {
    id: "blr-shivajinagar",
    name: "Shivajinagar",
    locality: "Shivajinagar",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["shiv", "shiva", "shivaji", "shivajinagar bus stand", "russell market", "commercial street"],
    lat: 12.9857,
    lng: 77.6057,
  },
  {
    id: "blr-koramangala",
    name: "Koramangala",
    locality: "Koramangala (All Blocks)",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["kor", "kora", "koramangala 1st block", "koramangala 4th block", "koramangala 5th block", "forum mall"],
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: "blr-indiranagar",
    name: "Indiranagar",
    locality: "Indiranagar 100ft Road",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["ind", "indi", "indira nagar", "100ft road indiranagar", "cmh road"],
    lat: 12.9784,
    lng: 77.6408,
  },
  {
    id: "blr-banashankari",
    name: "Banashankari",
    locality: "Banashankari (BSK 1st/2nd/3rd Stage)",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["ban", "bana", "bsk", "banashankari temple", "banashankari bus stand", "banashankari 2nd stage", "banashankari 3rd stage"],
    lat: 12.9255,
    lng: 77.5468,
  },
  {
    id: "blr-malleswaram",
    name: "Malleswaram",
    locality: "Malleswaram 8th/11th Cross",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["mal", "malle", "malleswaram 11th cross", "malleswaram 8th cross", "malleswaram pipeline road", "sampige road"],
    lat: 13.0031,
    lng: 77.5643,
  },
  {
    id: "blr-whitefield",
    name: "Whitefield",
    locality: "ITPL / Hope Farm / ECC Road",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["whi", "white", "itpl", "kadugodi", "hope farm", "whitefield main road"],
    lat: 12.9698,
    lng: 77.75,
  },
  {
    id: "blr-jayanagar",
    name: "Jayanagar",
    locality: "Jayanagar 4th/9th Block",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["jay", "jaya", "jayanagar 4th block", "jayanagar 3rd block", "jayanagar 9th block", "south end circle"],
    lat: 12.9308,
    lng: 77.5838,
  },
  {
    id: "blr-hsr-layout",
    name: "HSR Layout",
    locality: "HSR Layout (Sectors 1-7)",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["hsr", "hsr sector 1", "hsr sector 2", "hsr sector 3", "hsr sector 4", "hsr sector 6", "hsr sector 7", "27th main hsr"],
    lat: 12.9121,
    lng: 77.6446,
  },
  {
    id: "blr-electronic-city",
    name: "Electronic City",
    locality: "Electronic City Phase 1 & 2",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["elec", "ecity", "electronic city phase 1", "electronic city phase 2", "velankani", "wipro ecity", "infosys ecity"],
    lat: 12.8452,
    lng: 77.6602,
  },
  {
    id: "blr-marathahalli",
    name: "Marathahalli",
    locality: "Marathahalli Bridge / Outer Ring Road",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["mar", "marath", "marathahalli bridge", "kalamandir marathahalli", "innovative multiplex"],
    lat: 12.9591,
    lng: 77.6974,
  },
  {
    id: "blr-bellandur",
    name: "Bellandur",
    locality: "EcoSpace / Outer Ring Road",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["bel", "bell", "ecospace", "ecoworld", "bellandur gate", "central mall bellandur"],
    lat: 12.926,
    lng: 77.6762,
  },
  {
    id: "blr-yelahanka",
    name: "Yelahanka",
    locality: "Yelahanka New Town / Old Town",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["yel", "yela", "yelahanka new town", "yelahanka air force", "kogilu cross"],
    lat: 13.1007,
    lng: 77.5963,
  },
  {
    id: "blr-hebbal",
    name: "Hebbal",
    locality: "Hebbal Flyover / Manyata Tech Park",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["heb", "hebbal flyover", "manyata", "manyata tech park", "nagawara", "hebbal ring road"],
    lat: 13.0358,
    lng: 77.597,
  },
  {
    id: "blr-majestic",
    name: "Majestic / Kempegowda Bus Station",
    locality: "Majestic Railway & Bus Terminal",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "transit",
    aliases: ["maj", "majestic", "kbs", "kempegowda bus station", "bangalore city railway station", "sangam theatre", "ksr bengaluru"],
    lat: 12.9778,
    lng: 77.5727,
  },
  {
    id: "blr-yeshwanthpur",
    name: "Yeshwanthpur",
    locality: "Yeshwanthpur Railway Station / APMC",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "transit",
    aliases: ["yesh", "yeshwanthpur station", "orion mall", "yeshwantpur metro", "goverdhan theatre"],
    lat: 13.0227,
    lng: 77.5492,
  },
  {
    id: "blr-kia-airport",
    name: "Kempegowda International Airport (BLR)",
    locality: "Devanahalli / Terminal 1 & 2",
    city: "Bengaluru",
    district: "Bengaluru Rural",
    state: "Karnataka",
    country: "India",
    type: "airport",
    aliases: ["kem", "blr", "airport", "bangalore airport", "kia", "kia terminal 1", "kia terminal 2", "kempegowda airport", "devanahalli airport"],
    lat: 13.1986,
    lng: 77.7066,
  },
  {
    id: "blr-kr-puram",
    name: "K.R. Puram",
    locality: "Krishnarajapuram / Hanging Bridge",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["kr puram", "krishnarajapuram", "kr puram railway station", "hanging bridge"],
    lat: 13.0075,
    lng: 77.6959,
  },
  {
    id: "blr-vijayanagar",
    name: "Vijayanagar",
    locality: "Vijayanagar Club / Pipeline",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["vij", "vijay", "vijayanagar metro", "rpc layout", "maruthi mandir"],
    lat: 12.9719,
    lng: 77.5362,
  },
  {
    id: "blr-btm-layout",
    name: "BTM Layout",
    locality: "BTM 1st & 2nd Stage",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["btm", "btm 1st stage", "btm 2nd stage", "mico layout", "udupi garden"],
    lat: 12.9166,
    lng: 77.6101,
  },
  {
    id: "blr-jp-nagar",
    name: "JP Nagar",
    locality: "JP Nagar (Phases 1 to 9)",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["jp", "jp nagar 1st phase", "jp nagar 2nd phase", "jp nagar 6th phase", "jp nagar 7th phase", "sarakki"],
    lat: 12.9063,
    lng: 77.5857,
  },
  {
    id: "blr-basavanagudi",
    name: "Basavanagudi",
    locality: "Bull Temple Road / Gandhi Bazaar",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    type: "locality",
    aliases: ["bas", "basa", "basavanagudi", "bull temple", "gandhi bazaar", "d absurdity circle", "national college"],
    lat: 12.9421,
    lng: 77.5753,
  },

  // ── KARNATAKA CITIES & DISTRICTS ──
  {
    id: "ka-shivamogga",
    name: "Shivamogga",
    locality: "Shimoga City / Jog Falls Route",
    city: "Shivamogga",
    district: "Shivamogga",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["shiv", "shivamogga", "shimoga", "jog falls", "bhadravathi", "thirthahalli", "sagara"],
    lat: 13.9299,
    lng: 75.5681,
  },
  {
    id: "ka-mysuru",
    name: "Mysuru",
    locality: "Mysore Palace / Chamundi Hills",
    city: "Mysuru",
    district: "Mysuru",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["mys", "mysore", "mysuru", "chamundi hill", "brindavan gardens", "mysore palace"],
    lat: 12.2958,
    lng: 76.6394,
  },
  {
    id: "ka-coorg",
    name: "Coorg (Madikeri)",
    locality: "Madikeri / Kushalnagar / Virajpet",
    city: "Madikeri",
    district: "Kodagu",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["coo", "coorg", "madikeri", "kodagu", "kushalnagar", "raja seat", "abbey falls", "talacauvery"],
    lat: 12.4244,
    lng: 75.7382,
  },
  {
    id: "ka-chikmagalur",
    name: "Chikmagalur",
    locality: "Mullayanagiri / Coffee Plantations",
    city: "Chikmagalur",
    district: "Chikkamagaluru",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["chik", "chikmagalur", "chikkamagaluru", "mullayanagiri", "baba budangiri", "kemmangundi"],
    lat: 13.3153,
    lng: 75.7754,
  },
  {
    id: "ka-mangaluru",
    name: "Mangaluru",
    locality: "Mangalore Coast / Panambur",
    city: "Mangaluru",
    district: "Dakshina Kannada",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["man", "mang", "mangaluru", "mangalore", "panambur", "kudroli", "surathkal"],
    lat: 12.9141,
    lng: 74.856,
  },
  {
    id: "ka-udupi",
    name: "Udupi",
    locality: "Sri Krishna Matha / Malpe Beach",
    city: "Udupi",
    district: "Udupi",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["udu", "udupi", "malpe", "manipal", "kaup beach", "st mary island"],
    lat: 13.3409,
    lng: 74.7421,
  },
  {
    id: "ka-hubballi",
    name: "Hubballi-Dharwad",
    locality: "Twin Cities Hubli / Dharwad",
    city: "Hubballi",
    district: "Dharwad",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["hub", "hubli", "hubballi", "dharwad", "unakal lake"],
    lat: 15.3647,
    lng: 75.124,
  },
  {
    id: "ka-belagavi",
    name: "Belagavi",
    locality: "Belgaum Fort / City Center",
    city: "Belagavi",
    district: "Belagavi",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["bel", "belgaum", "belagavi", "gokak falls"],
    lat: 15.8497,
    lng: 74.4977,
  },
  {
    id: "ka-hassan",
    name: "Hassan (Belur & Halebidu)",
    locality: "Hassan City / Hoysala Temples",
    city: "Hassan",
    district: "Hassan",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["has", "hassan", "belur", "halebidu", "shravanabelagola", "shettihalli church"],
    lat: 13.0033,
    lng: 76.1004,
  },
  {
    id: "ka-hampi",
    name: "Hampi (Vijayanagara)",
    locality: "UNESCO World Heritage Site",
    city: "Hosapete",
    district: "Vijayanagara",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["ham", "hampi", "vijayanagara", "hosapete", "hospet", "virupaksha temple", "stone chariot"],
    lat: 15.335,
    lng: 76.46,
  },
  {
    id: "ka-gokarna",
    name: "Gokarna",
    locality: "Om Beach / Mahabaleshwar Temple",
    city: "Gokarna",
    district: "Uttara Kannada",
    state: "Karnataka",
    country: "India",
    type: "tourist",
    aliases: ["gok", "gokarna", "om beach", "kudle beach", "murudeshwar"],
    lat: 14.5479,
    lng: 74.3188,
  },
  {
    id: "ka-davanagere",
    name: "Davanagere",
    locality: "Davanagere City / Benne Dosa Center",
    city: "Davanagere",
    district: "Davanagere",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["dav", "davanagere", "davangere", "harihar"],
    lat: 14.4644,
    lng: 75.9218,
  },
  {
    id: "ka-tumakuru",
    name: "Tumakuru",
    locality: "Tumkur City / Siddaganga Matha",
    city: "Tumakuru",
    district: "Tumakuru",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["tum", "tumkur", "tumakuru", "siddaganga", "devarayanadurga"],
    lat: 13.3379,
    lng: 77.1021,
  },
  {
    id: "ka-ballari",
    name: "Ballari",
    locality: "Bellary Fort",
    city: "Ballari",
    district: "Ballari",
    state: "Karnataka",
    country: "India",
    type: "city",
    aliases: ["bal", "ballari", "bellary", "toranagallu"],
    lat: 15.1394,
    lng: 76.9214,
  },

  // ── SOUTH INDIA TOURIST DESTINATIONS & OUTSTATION CITIES ──
  {
    id: "ap-tirupati",
    name: "Tirupati",
    locality: "Tirumala Balaji Temple / Alipiri",
    city: "Tirupati",
    district: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    type: "tourist",
    aliases: ["tir", "tiru", "tirupati", "tirumala", "balaji", "sri venkateswara", "alipiri", "renigunta"],
    lat: 13.6288,
    lng: 79.4192,
  },
  {
    id: "tn-ooty",
    name: "Ooty (Udhagamandalam)",
    locality: "Nilgiris / Botanical Gardens / Coonoor",
    city: "Ooty",
    district: "Nilgiris",
    state: "Tamil Nadu",
    country: "India",
    type: "tourist",
    aliases: ["oot", "ooty", "nilgiris", "coonoor", "doddabetta", "pykara", "kotagiri"],
    lat: 11.4102,
    lng: 76.695,
  },
  {
    id: "kl-wayanad",
    name: "Wayanad",
    locality: "Kalpetta / Sulthan Bathery / Vythiri",
    city: "Kalpetta",
    district: "Wayanad",
    state: "Kerala",
    country: "India",
    type: "tourist",
    aliases: ["way", "wayanad", "kalpetta", "sulthan bathery", "chembra peak", "banasura", "edakkal"],
    lat: 11.6854,
    lng: 76.132,
  },
  {
    id: "kl-munnar",
    name: "Munnar",
    locality: "Tea Gardens / Mattupetty / Anamudi",
    city: "Munnar",
    district: "Idukki",
    state: "Kerala",
    country: "India",
    type: "tourist",
    aliases: ["mun", "munnar", "idukki", "mattupetty", "top station"],
    lat: 10.0889,
    lng: 77.0595,
  },
  {
    id: "kl-alleppey",
    name: "Alleppey (Alappuzha)",
    locality: "Vembanad Lake / Backwaters & Houseboats",
    city: "Alappuzha",
    district: "Alappuzha",
    state: "Kerala",
    country: "India",
    type: "tourist",
    aliases: ["all", "alleppey", "alappuzha", "backwaters", "houseboat", "vembanad"],
    lat: 9.4981,
    lng: 76.3388,
  },
  {
    id: "tn-kodaikanal",
    name: "Kodaikanal",
    locality: "Princess of Hill Stations / Kodai Lake",
    city: "Kodaikanal",
    district: "Dindigul",
    state: "Tamil Nadu",
    country: "India",
    type: "tourist",
    aliases: ["kod", "kodaikanal", "kodai", "pillar rocks", "coakers walk"],
    lat: 10.2381,
    lng: 77.4892,
  },
  {
    id: "ga-goa",
    name: "Goa (North & South)",
    locality: "Panaji / Calangute / Baga / Margao",
    city: "Panaji",
    district: "North Goa",
    state: "Goa",
    country: "India",
    type: "tourist",
    aliases: ["goa", "north goa", "south goa", "calangute", "baga", "panjim", "panaji", "madgaon"],
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: "tn-chennai",
    name: "Chennai",
    locality: "Marina Beach / Central Station / Airport",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    type: "city",
    aliases: ["che", "chennai", "madras", "central station chennai", "t nagar", "omr"],
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "ts-hyderabad",
    name: "Hyderabad",
    locality: "HITEC City / Secunderabad / Charminar",
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "city",
    aliases: ["hyd", "hyderabad", "secunderabad", "hitec city", "gachibowli", "cyberabad"],
    lat: 17.385,
    lng: 78.4867,
  },
  {
    id: "py-pondicherry",
    name: "Puducherry (Pondicherry)",
    locality: "White Town / Promenade Beach / Auroville",
    city: "Puducherry",
    district: "Puducherry",
    state: "Puducherry",
    country: "India",
    type: "tourist",
    aliases: ["pon", "pondicherry", "puducherry", "auroville", "white town", "promenade beach"],
    lat: 11.9416,
    lng: 79.8083,
  },
  {
    id: "tn-coimbatore",
    name: "Coimbatore",
    locality: "Gandhipuram / RS Puram / Isha Yoga",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    type: "city",
    aliases: ["cbe", "coimbatore", "kovai", "isha yoga center"],
    lat: 11.0168,
    lng: 76.9558,
  },
  {
    id: "tn-madurai",
    name: "Madurai",
    locality: "Meenakshi Amman Temple / City Center",
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    country: "India",
    type: "tourist",
    aliases: ["mad", "madurai", "meenakshi temple", "thiruparankundram"],
    lat: 9.9252,
    lng: 78.1198,
  },
  {
    id: "tn-rameshwaram",
    name: "Rameshwaram",
    locality: "Ramanathaswamy Temple / Dhanushkodi",
    city: "Rameshwaram",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    type: "tourist",
    aliases: ["ram", "rameshwaram", "dhanushkodi", "pamban bridge", "ramanathaswamy"],
    lat: 9.2876,
    lng: 79.3129,
  },
  {
    id: "kl-kochi",
    name: "Kochi (Cochin)",
    locality: "Fort Kochi / Marine Drive / Airport",
    city: "Kochi",
    district: "Ernakulam",
    state: "Kerala",
    country: "India",
    type: "city",
    aliases: ["koc", "kochi", "cochin", "ernakulam", "fort kochi", "nedumbassery airport"],
    lat: 9.9312,
    lng: 76.2673,
  },
];

/**
 * Searches locations with intelligent prefix, partial, and alias matching
 */
export function searchLocations(query: string, limit = 8): LocationItem[] {
  if (!query || query.trim().length === 0) {
    return SOUTH_INDIA_LOCATIONS.slice(0, limit);
  }

  const q = query.trim().toLowerCase();

  const scored = SOUTH_INDIA_LOCATIONS.map((loc) => {
    let score = 0;
    const nameLower = loc.name.toLowerCase();
    const cityLower = loc.city.toLowerCase();
    const localityLower = loc.locality?.toLowerCase() ?? "";

    // 1. Exact name match
    if (nameLower === q) score += 100;
    // 2. Starts with query on name
    else if (nameLower.startsWith(q)) score += 75;
    // 3. Name contains query word
    else if (nameLower.includes(q)) score += 50;

    // 4. City starts with or contains
    if (cityLower.startsWith(q)) score += 40;
    else if (cityLower.includes(q)) score += 20;

    // 5. Locality match
    if (localityLower.startsWith(q)) score += 30;
    else if (localityLower.includes(q)) score += 15;

    // 6. Alias match
    if (loc.aliases && loc.aliases.some((a) => a === q)) score += 60;
    else if (loc.aliases && loc.aliases.some((a) => a.startsWith(q))) score += 35;
    else if (loc.aliases && loc.aliases.some((a) => a.includes(q))) score += 20;

    return { loc, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((s) => s.loc)
    .slice(0, limit);
}
