const { Client } = require("pg");

const client = new Client({
  connectionString:
    "postgresql://soupa839:5yLMTWjNFmPByXLA8d47Zvdnz@168.119.64.101:5432/soupa839?sslmode=disable",
});

async function main() {
  await client.connect();
  console.log("Connected to PostgreSQL");

  // 1. Sync FAQs if empty
  const faqCheck = await client.query("SELECT count(*) FROM public.faqs");
  if (parseInt(faqCheck.rows[0].count, 10) === 0) {
    console.log("Seeding FAQs into public.faqs...");
    const faqs = [
      {
        question: "What is the booking process for Force Urbania or tempo traveller in Bangalore?",
        answer: "You can book directly via our website enquiry form, WhatsApp at +91 99808 61000, or by calling our customer care. Share your trip dates, passenger count, pickup location, and itinerary. We will provide an instant transparent quote. You can confirm by paying a token advance with instant digital confirmation.",
        category: "Booking",
        display_order: 1,
      },
      {
        question: "What are the per-km rates for Force Urbania in Bangalore?",
        answer: "Force Urbania rental rates start from ₹30/km for 10-seater premium and go up to ₹38/km for 10-seater Maharaja and ₹42/km for 12-seater Maharaja. For local Bangalore city travel, 8-hour / 80-km packages start from ₹5,000.",
        category: "Pricing",
        display_order: 2,
      },
      {
        question: "What is included in the rental price?",
        answer: "Our rental charges include the vehicle, professional commercial chauffeur allowance, and standard vehicle maintenance. Toll fees, interstate permit charges, and parking fees are billed at actuals based on government receipts.",
        category: "Pricing",
        display_order: 3,
      },
      {
        question: "Are outstation driver allowances and night charges included?",
        answer: "Driver allowance (Bata) is typically ₹500 to ₹700 per calendar day depending on the vehicle category. For night driving between 10:00 PM and 6:00 AM, a nominal night charge applies.",
        category: "Outstation",
        display_order: 4,
      },
      {
        question: "Can we hire Force Urbania or Innova Crysta for outstation South India tours?",
        answer: "Yes, all our fleet vehicles are commercially registered with valid All-India Tourist Permits (AITP). We regularly operate trips from Bangalore to Mysore, Coorg, Ooty, Wayanad, Kodaikanal, Tirupati, Pondicherry, and Chikmagalur.",
        category: "Outstation",
        display_order: 5,
      },
      {
        question: "What is your cancellation and refund policy?",
        answer: "Cancellations made 48 hours before pickup receive a 100% refund of the advance. Cancellations between 24–48 hours receive a 50% refund. Cancellations within 24 hours of scheduled departure are non-refundable.",
        category: "Cancellation",
        display_order: 6,
      },
    ];

    for (const f of faqs) {
      await client.query(
        `INSERT INTO public.faqs (question, answer, category, display_order, is_active)
         VALUES ($1, $2, $3, $4, true)`,
        [f.question, f.answer, f.category, f.display_order]
      );
    }
    console.log(`Seeded ${faqs.length} FAQs.`);
  }

  // 2. Ensure urbania_rates exists in pricing_rules
  const urbaniaCheck = await client.query(
    "SELECT id FROM public.pricing_rules WHERE key = 'urbania_rates'"
  );
  if (urbaniaCheck.rows.length === 0) {
    console.log("Seeding default urbania_rates into pricing_rules...");
    const rates = [
      {
        id: "urb-prem-10",
        name: "PREMIUM 10 SEATER",
        slug: "10-seater-urbania",
        category: "Premium",
        seating_capacity: 10,
        seating_layout: "(4-2-2-2)",
        image: "/images/fleets/urbania-maharaja-10-seater.jpg",
        local_8hr_80km: 5000,
        local_12hr_100km: 6500,
        extra_km: 33,
        extra_hour: 500,
        outstation_per_km: 33,
        outstation_min_km_per_day: 300,
        driver_allowance: 700,
        is_active: true,
        display_order: 1,
      },
      {
        id: "urb-prem-12",
        name: "PREMIUM 12 SEATER",
        slug: "12-seater-urbania",
        category: "Premium",
        seating_capacity: 12,
        seating_layout: "(4-3-3-2)",
        image: "/images/fleets/urbania-12-seater.jpg",
        local_8hr_80km: 5500,
        local_12hr_100km: 7200,
        extra_km: 36,
        extra_hour: 550,
        outstation_per_km: 36,
        outstation_min_km_per_day: 300,
        driver_allowance: 700,
        is_active: true,
        display_order: 2,
      },
      {
        id: "urb-mod-16",
        name: "MODIFIED 16 SEATER",
        slug: "16-seater-urbania",
        category: "Premium",
        seating_capacity: 16,
        seating_layout: "(2x1 + Last Row)",
        image: "/images/fleets/urbania-16-seater.jpg",
        local_8hr_80km: 6500,
        local_12hr_100km: 8500,
        extra_km: 40,
        extra_hour: 650,
        outstation_per_km: 40,
        outstation_min_km_per_day: 300,
        driver_allowance: 800,
        is_active: true,
        display_order: 3,
      },
      {
        id: "urb-lux-9",
        name: "MAHARAJA 9 SEATER",
        slug: "9-seater-luxury-urbania",
        category: "Luxury / Maharaja",
        seating_capacity: 9,
        seating_layout: "(1x1 VIP Captain)",
        image: "/images/fleets/urbania-9-seater-luxury.jpg",
        local_8hr_80km: 4800,
        local_12hr_100km: 6200,
        extra_km: 32,
        extra_hour: 450,
        outstation_per_km: 32,
        outstation_min_km_per_day: 300,
        driver_allowance: 700,
        is_active: true,
        display_order: 4,
      },
      {
        id: "urb-mah-10",
        name: "MAHARAJA 10 SEATER",
        slug: "10-seater-maharaja-urbania",
        category: "Luxury / Maharaja",
        seating_capacity: 10,
        seating_layout: "(1x1 VIP Recliners)",
        image: "/images/fleets/urbania-maharaja-10-seater.jpg",
        local_8hr_80km: 6000,
        local_12hr_100km: 7800,
        extra_km: 38,
        extra_hour: 500,
        outstation_per_km: 38,
        outstation_min_km_per_day: 300,
        driver_allowance: 700,
        is_active: true,
        display_order: 5,
      },
      {
        id: "urb-mah-12",
        name: "MAHARAJA 12 SEATER",
        slug: "12-seater-maharaja-urbania",
        category: "Luxury / Maharaja",
        seating_capacity: 12,
        seating_layout: "(1x1 Ultra Luxury)",
        image: "/images/fleets/urbania-maharaja-12-seater.jpg",
        local_8hr_80km: 6800,
        local_12hr_100km: 8800,
        extra_km: 42,
        extra_hour: 550,
        outstation_per_km: 42,
        outstation_min_km_per_day: 300,
        driver_allowance: 700,
        is_active: true,
        display_order: 6,
      },
    ];

    await client.query(
      `INSERT INTO public.pricing_rules (key, value_json, description)
       VALUES ('urbania_rates', $1, 'Force Urbania & Maharaja fleet rates')`,
      [JSON.stringify(rates)]
    );
    console.log("Seeded urbania_rates.");
  }

  // 3. Upsert / Sync complete DEFAULT_FLEETS into public.fleets
  console.log("Syncing all vehicles into public.fleets...");
  const fleets = [
    {
      slug: "innova-crysta",
      name: "Toyota Innova Crysta",
      category: "PREMIUM MPV",
      seating: 7,
      seating_label: "6+1 seater",
      luggage: "4-5 Large Suitcases",
      ac: true,
      suitable_for: ["Family Outstation", "Corporate Travel", "Airport Transfer", "Wedding Transport"],
      starting_price: 20,
      short_description: "Bangalore's most trusted 7-seater MPV with pushback reclining captain seats and powerful dual AC.",
      description: "The Toyota Innova Crysta is the gold standard for Indian road travel. Renowned for its unmatched passenger comfort, bulletproof reliability, and effortless highway cruising.",
      image_url: "/images/fleets/cars/innova-crysta.jpg",
      features: ["7 Ergonomic Captain Seats", "Dual AC Vents", "Touchscreen Audio", "Uniformed Chauffeur"],
      is_featured: true,
      is_active: true,
      display_order: 1,
      model: "Toyota Innova Crysta 2.4 VX/ZX",
      min_km: 300,
      per_km_rate: 20,
      driver_allowance: 400,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 3500,
      extra_hour_rate: 200,
      extra_km_rate: 20,
    },
    {
      slug: "innova-hycross-hybrid",
      name: "Toyota Innova Hycross Hybrid",
      category: "HYBRID LUXURY MPV",
      seating: 7,
      seating_label: "6+1 seater",
      luggage: "4-5 Large Suitcases",
      ac: true,
      suitable_for: ["Executive Corporate", "VIP Airport Transfer", "Luxury Family Trips"],
      starting_price: 25,
      short_description: "Next-generation self-charging hybrid luxury MPV with quiet electric cabin mode and lounge captain seats.",
      description: "Experience futuristic road luxury with the Toyota Innova Hycross Hybrid. First-class Ottoman reclining seats, ambient cabin glow, and multi-zone climate control.",
      image_url: "/images/fleets/cars/innova-hycross-hybrid.jpg",
      features: ["Silent EV Mode", "Ottoman Recliners", "Multi-Zone Climate Control", "Apple CarPlay"],
      is_featured: true,
      is_active: true,
      display_order: 2,
      model: "Toyota Innova Hycross Hybrid ZX(O)",
      min_km: 300,
      per_km_rate: 25,
      driver_allowance: 500,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 3750,
      extra_hour_rate: 250,
      extra_km_rate: 25,
    },
    {
      slug: "fortuner",
      name: "Toyota Fortuner",
      category: "PREMIUM LUXURY SUV",
      seating: 7,
      seating_label: "6+1 seater",
      luggage: "4 Large Suitcases",
      ac: true,
      suitable_for: ["VIP Delegates", "Executive Travel", "Wedding Transport"],
      starting_price: 65,
      short_description: "The ultimate high-commanding 6+1 seater luxury SUV with imposing road presence.",
      description: "Command the road in prestige with the Toyota Fortuner. Built with a muscular body, luxury dark chamois leather upholstery, and high-potency 2.8L diesel engine.",
      image_url: "/images/fleets/cars/fortuner.jpg",
      features: ["Imposing Stance", "Dark Leather Interior", "JBL Premium Audio", "Vehicle Stability Control"],
      is_featured: true,
      is_active: true,
      display_order: 3,
      model: "Toyota Fortuner 4x2 / 4x4 Automatic",
      min_km: 300,
      per_km_rate: 65,
      driver_allowance: 500,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 6500,
      extra_hour_rate: 650,
      extra_km_rate: 65,
    },
    {
      slug: "ertiga",
      name: "Maruti Suzuki Ertiga",
      category: "ECONOMY MUV",
      seating: 6,
      seating_label: "6+1 seater",
      luggage: "2-3 Suitcases",
      ac: true,
      suitable_for: ["Budget Family Outstation", "Airport Drop", "City Sightseeing"],
      starting_price: 15,
      short_description: "Affordable and fuel-efficient 6+1 seater MUV for small family city and outstation journeys.",
      description: "Smart, economical, and comfortable transport for up to 6 passengers.",
      image_url: "/images/fleets/cars/ertiga.jpg",
      features: ["6 Passenger Seating", "Chilled AC", "Clean Cabin", "Experienced Driver"],
      is_featured: true,
      is_active: true,
      display_order: 4,
      model: "Maruti Suzuki Ertiga Smart Hybrid",
      min_km: 250,
      per_km_rate: 15,
      driver_allowance: 400,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 2600,
      extra_hour_rate: 180,
      extra_km_rate: 16,
    },
    {
      slug: "10-seater-urbania",
      name: "10 Seater Force Urbania (Premium)",
      category: "PREMIUM URBANIA",
      seating: 10,
      seating_label: "9+1 / 10+1 Seater",
      luggage: "6-8 Suitcases",
      ac: true,
      suitable_for: ["Corporate Offsite", "Family Outstation", "Airport Transfers"],
      starting_price: 33,
      short_description: "Modern German-engineered luxury van with individual AC vents and plush reclining seats.",
      description: "Force Urbania 10-seater delivers high-roof luxury, panoramic windows, and smooth air suspension for Bangalore outstation trips.",
      image_url: "/images/fleets/urbania-maharaja-10-seater.jpg",
      features: ["High Roof Walkthrough", "Plush Recliners", "Individual AC", "USB Ports"],
      is_featured: true,
      is_active: true,
      display_order: 5,
      model: "Force Urbania 3615 WB 10 Seater",
      min_km: 300,
      per_km_rate: 33,
      driver_allowance: 700,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 5000,
      local_package_12h_km: 100,
      local_package_12h_rate: 6500,
      extra_hour_rate: 500,
      extra_km_rate: 33,
    },
    {
      slug: "12-seater-urbania",
      name: "12 Seater Force Urbania (Premium)",
      category: "PREMIUM URBANIA",
      seating: 12,
      seating_label: "11+1 / 12+1 Seater",
      luggage: "8-10 Suitcases",
      ac: true,
      suitable_for: ["Group Tours", "Corporate Shuttle", "Wedding Travel"],
      starting_price: 36,
      short_description: "12 passenger capacity with individual high-back reclining seats and large boot space.",
      description: "Force Urbania 12 Seater is the favorite choice for South India group tours with generous legroom and silent air suspension.",
      image_url: "/images/fleets/urbania-12-seater.jpg",
      features: ["Ergonomic 2x1 Layout", "LED Mood Lights", "High Roof Stand-up Cabin", "Digital Audio"],
      is_featured: true,
      is_active: true,
      display_order: 6,
      model: "Force Urbania 3615 WB 12 Seater",
      min_km: 300,
      per_km_rate: 36,
      driver_allowance: 700,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 5500,
      local_package_12h_km: 100,
      local_package_12h_rate: 7200,
      extra_hour_rate: 550,
      extra_km_rate: 36,
    },
    {
      slug: "16-seater-urbania",
      name: "16 Seater Force Urbania (Premium)",
      category: "PREMIUM URBANIA",
      seating: 16,
      seating_label: "15+1 / 16+1 Seater",
      luggage: "10-12 Suitcases",
      ac: true,
      suitable_for: ["Large Group Outstation", "Corporate Delegations", "Wedding Baraat"],
      starting_price: 40,
      short_description: "Long wheelbase 16-seater luxury van with top-grade comfort for big families and delegations.",
      description: "Force Urbania 16 Seater offers expansive seating layout, high ground clearance, and ultra-smooth highway cruising.",
      image_url: "/images/fleets/urbania-16-seater.jpg",
      features: ["Long Wheelbase 4400 WB", "Generous Overhead Racks", "Dual AC Compressors", "Pushback Seats"],
      is_featured: true,
      is_active: true,
      display_order: 7,
      model: "Force Urbania 4400 WB 16 Seater",
      min_km: 300,
      per_km_rate: 40,
      driver_allowance: 800,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 6500,
      local_package_12h_km: 100,
      local_package_12h_rate: 8500,
      extra_hour_rate: 650,
      extra_km_rate: 40,
    },
    {
      slug: "9-seater-luxury-urbania",
      name: "9 Seater Urbania Maharaja (VIP)",
      category: "LUXURY / MAHARAJA",
      seating: 9,
      seating_label: "8+1 VIP Captain",
      luggage: "6 Large Suitcases",
      ac: true,
      suitable_for: ["VIP Delegates", "Celebrity Travel", "Luxury Wedding Escort"],
      starting_price: 32,
      short_description: "Custom Maharaja lounge modification with wide 1x1 captain recliners and ambient ceiling.",
      description: "Experience royal luxury travel in Bangalore. Individual sofa-style captain seats with armrests, cup holders, and 4K entertainment screen.",
      image_url: "/images/fleets/urbania-9-seater-luxury.jpg",
      features: ["1x1 Maharaja Sofa Recliners", "Starlight Mood Roof", "4K Smart TV & Karaoke", "Mini Bar Chiller"],
      is_featured: true,
      is_active: true,
      display_order: 8,
      model: "Force Urbania Maharaja 9 Seater Edition",
      min_km: 300,
      per_km_rate: 32,
      driver_allowance: 700,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 4800,
      local_package_12h_km: 100,
      local_package_12h_rate: 6200,
      extra_hour_rate: 450,
      extra_km_rate: 32,
    },
    {
      slug: "10-seater-maharaja-urbania",
      name: "10 Seater Urbania Maharaja (VIP)",
      category: "LUXURY / MAHARAJA",
      seating: 10,
      seating_label: "9+1 VIP Recliners",
      luggage: "7 Large Suitcases",
      ac: true,
      suitable_for: ["VIP Corporate", "Luxury Family Holidays", "Executive Retreats"],
      starting_price: 38,
      short_description: "Ultra-luxurious Maharaja customized interior with 10 VIP recliner seats and motorized curtains.",
      description: "Custom-crafted for elite travellers. Includes motorized calf support, premium Italian leatherette, and high-fidelity surround sound.",
      image_url: "/images/fleets/urbania-maharaja-10-seater.jpg",
      features: ["VIP Italian Leather Recliners", "Touchscreen Controls", "Surround Sound Audio", "Motorized Curtains"],
      is_featured: true,
      is_active: true,
      display_order: 9,
      model: "Force Urbania Maharaja 10 Seater Edition",
      min_km: 300,
      per_km_rate: 38,
      driver_allowance: 700,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 6000,
      local_package_12h_km: 100,
      local_package_12h_rate: 7800,
      extra_hour_rate: 500,
      extra_km_rate: 38,
    },
    {
      slug: "12-seater-maharaja-urbania",
      name: "12 Seater Urbania Maharaja (VIP)",
      category: "LUXURY / MAHARAJA",
      seating: 12,
      seating_label: "11+1 VIP Luxury",
      luggage: "8 Large Suitcases",
      ac: true,
      suitable_for: ["VIP Delegations", "Luxury Pilgrimage Tours", "Family Reunions"],
      starting_price: 42,
      short_description: "Top-of-the-line 12-seater Maharaja with plush executive seats and premier amenities.",
      description: "The pinnacle of van luxury in India. Ideal for South India heritage circuits and executive business retreats.",
      image_url: "/images/fleets/urbania-maharaja-12-seater.jpg",
      features: ["VIP Reclining Captains", "Full Ambient Lighting", "Wireless Charging", "High-Fi Audio"],
      is_featured: true,
      is_active: true,
      display_order: 10,
      model: "Force Urbania Maharaja 12 Seater Edition",
      min_km: 300,
      per_km_rate: 42,
      driver_allowance: 700,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 6800,
      local_package_12h_km: 100,
      local_package_12h_rate: 8800,
      extra_hour_rate: 550,
      extra_km_rate: 42,
    },
    {
      slug: "9-seater-tempo-traveller",
      name: "9 Seater Luxury Tempo Traveller",
      category: "TEMPO TRAVELLER",
      seating: 9,
      seating_label: "8+1 / 9+1 Seater",
      luggage: "5-6 Suitcases",
      ac: true,
      suitable_for: ["Mysore Tour", "Ooty Family Trip", "Airport Shuttles"],
      starting_price: 24,
      short_description: "Comfortable pushback 9-seater tempo traveller with AC and ample luggage boot.",
      description: "Standard luxury tempo traveller with verified driver for Bangalore city and outstation journeys.",
      image_url: "/images/fleets/tempo-12-seater-interior.png",
      features: ["Pushback 1x1 Seats", "Chilled AC", "Music System", "Large Boot"],
      is_featured: false,
      is_active: true,
      display_order: 11,
      model: "Force Tempo Traveller 3350 WB",
      min_km: 300,
      per_km_rate: 24,
      driver_allowance: 500,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 4200,
      extra_hour_rate: 400,
      extra_km_rate: 24,
    },
    {
      slug: "12-seater-tempo-traveller",
      name: "12 Seater Deluxe Tempo Traveller",
      category: "TEMPO TRAVELLER",
      seating: 12,
      seating_label: "11+1 / 12+1 Seater",
      luggage: "7-8 Suitcases",
      ac: true,
      suitable_for: ["Coorg Hills", "Tirupati Darshan", "Corporate Outings"],
      starting_price: 26,
      short_description: "Most popular 12-seater tourist vehicle with 2x1 pushback layout and rooftop luggage carrier.",
      description: "Well-maintained 12-seater tempo traveller with professional driver, ideal for hill stations and temple tours.",
      image_url: "/images/fleets/tempo-12-seater-interior.png",
      features: ["2x1 Pushback Seats", "Rear Chilled AC", "LED TV & Audio", "Roof Carrier"],
      is_featured: false,
      is_active: true,
      display_order: 12,
      model: "Force Tempo Traveller 3350 WB",
      min_km: 300,
      per_km_rate: 26,
      driver_allowance: 500,
      local_package_hours: 8,
      local_package_km: 80,
      local_package_rate: 4600,
      extra_hour_rate: 400,
      extra_km_rate: 26,
    },
  ];

  for (const f of fleets) {
    const existing = await client.query(
      "SELECT id FROM public.fleets WHERE slug = $1 OR lower(name) = lower($2)",
      [f.slug, f.name]
    );

    if (existing.rows.length > 0) {
      await client.query(
        `UPDATE public.fleets SET
          slug = $2,
          name = $3,
          category = $4,
          seating = $5,
          seating_label = $6,
          luggage = $7,
          ac = $8,
          suitable_for = $9,
          starting_price = $10,
          short_description = $11,
          description = $12,
          image_url = $13,
          features = $14,
          is_featured = $15,
          is_active = $16,
          display_order = $17,
          model = $18,
          min_km = $19,
          per_km_rate = $20,
          driver_allowance = $21,
          local_package_hours = $22,
          local_package_km = $23,
          local_package_rate = $24,
          local_package_12h_km = $25,
          local_package_12h_rate = $26,
          extra_hour_rate = $27,
          extra_km_rate = $28,
          updated_at = now()
        WHERE id = $1`,
        [
          existing.rows[0].id,
          f.slug,
          f.name,
          f.category,
          f.seating,
          f.seating_label,
          f.luggage,
          f.ac,
          f.suitable_for,
          f.starting_price,
          f.short_description,
          f.description,
          f.image_url,
          f.features,
          f.is_featured,
          f.is_active,
          f.display_order,
          f.model,
          f.min_km,
          f.per_km_rate,
          f.driver_allowance,
          f.local_package_hours,
          f.local_package_km,
          f.local_package_rate,
          f.local_package_12h_km || null,
          f.local_package_12h_rate || null,
          f.extra_hour_rate,
          f.extra_km_rate,
        ]
      );
      console.log(`Updated fleet ${f.name} (${f.slug})`);
    } else {
      await client.query(
        `INSERT INTO public.fleets (
          slug, name, category, seating, seating_label, luggage, ac, suitable_for,
          starting_price, short_description, description, image_url, features,
          is_featured, is_active, display_order, model, min_km, per_km_rate,
          driver_allowance, local_package_hours, local_package_km, local_package_rate,
          local_package_12h_km, local_package_12h_rate, extra_hour_rate, extra_km_rate
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8,
          $9, $10, $11, $12, $13,
          $14, $15, $16, $17, $18, $19,
          $20, $21, $22, $23,
          $24, $25, $26, $27
        )`,
        [
          f.slug,
          f.name,
          f.category,
          f.seating,
          f.seating_label,
          f.luggage,
          f.ac,
          f.suitable_for,
          f.starting_price,
          f.short_description,
          f.description,
          f.image_url,
          f.features,
          f.is_featured,
          f.is_active,
          f.display_order,
          f.model,
          f.min_km,
          f.per_km_rate,
          f.driver_allowance,
          f.local_package_hours,
          f.local_package_km,
          f.local_package_rate,
          f.local_package_12h_km || null,
          f.local_package_12h_rate || null,
          f.extra_hour_rate,
          f.extra_km_rate,
        ]
      );
      console.log(`Inserted fleet ${f.name} (${f.slug})`);
    }
  }

  console.log("Database sync and seed completed successfully!");
  await client.end();
}

main().catch((e) => {
  console.error("Sync error:", e);
  process.exit(1);
});
