/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BookingProcedureRouteImport } from './routes/booking-procedure'
import { Route as BreakdownPolicyRouteImport } from './routes/breakdown-policy'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CrystaRouteImport } from './routes/crysta'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TravelInfoRouteImport } from './routes/travel-info'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as FleetsIndexRouteImport } from './routes/fleets.index'
import { Route as FleetsSlugRouteImport } from './routes/fleets.$slug'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingProcedureRoute = BookingProcedureRouteImport.update({
  id: '/booking-procedure',
  path: '/booking-procedure',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakdownPolicyRoute = BreakdownPolicyRouteImport.update({
  id: '/breakdown-policy',
  path: '/breakdown-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CrystaRoute = CrystaRouteImport.update({
  id: '/crysta',
  path: '/crysta',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelInfoRoute = TravelInfoRouteImport.update({
  id: '/travel-info',
  path: '/travel-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetsIndexRoute = FleetsIndexRouteImport.update({
  id: '/fleets/',
  path: '/fleets/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetsSlugRoute = FleetsSlugRouteImport.update({
  id: '/fleets/$slug',
  path: '/fleets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-procedure': typeof BookingProcedureRoute
  '/breakdown-policy': typeof BreakdownPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/crysta': typeof CrystaRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-info': typeof TravelInfoRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/fleets/$slug': typeof FleetsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/fleets/': typeof FleetsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-procedure': typeof BookingProcedureRoute
  '/breakdown-policy': typeof BreakdownPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/crysta': typeof CrystaRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-info': typeof TravelInfoRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/fleets/$slug': typeof FleetsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas': typeof AreasIndexRoute
  '/fleets': typeof FleetsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-procedure': typeof BookingProcedureRoute
  '/breakdown-policy': typeof BreakdownPolicyRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/crysta': typeof CrystaRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-info': typeof TravelInfoRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/fleets/$slug': typeof FleetsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/fleets/': typeof FleetsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/booking'
    | '/booking-procedure'
    | '/breakdown-policy'
    | '/cancellation-policy'
    | '/contact-us'
    | '/crysta'
    | '/destinations'
    | '/experiences'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/travel-info'
    | '/areas/$slug'
    | '/fleets/$slug'
    | '/packages/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/fleets/'
    | '/packages/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/booking'
    | '/booking-procedure'
    | '/breakdown-policy'
    | '/cancellation-policy'
    | '/contact-us'
    | '/crysta'
    | '/destinations'
    | '/experiences'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/travel-info'
    | '/areas/$slug'
    | '/fleets/$slug'
    | '/packages/$slug'
    | '/services/$slug'
    | '/areas'
    | '/fleets'
    | '/packages'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/booking'
    | '/booking-procedure'
    | '/breakdown-policy'
    | '/cancellation-policy'
    | '/contact-us'
    | '/crysta'
    | '/destinations'
    | '/experiences'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/testimonials'
    | '/travel-info'
    | '/areas/$slug'
    | '/fleets/$slug'
    | '/packages/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/fleets/'
    | '/packages/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  BookingProcedureRoute: typeof BookingProcedureRoute
  BreakdownPolicyRoute: typeof BreakdownPolicyRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactUsRoute: typeof ContactUsRoute
  CrystaRoute: typeof CrystaRoute
  DestinationsRoute: typeof DestinationsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TravelInfoRoute: typeof TravelInfoRoute
  AreasSlugRoute: typeof AreasSlugRoute
  FleetsSlugRoute: typeof FleetsSlugRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
  FleetsIndexRoute: typeof FleetsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-procedure': {
      id: '/booking-procedure'
      path: '/booking-procedure'
      fullPath: '/booking-procedure'
      preLoaderRoute: typeof BookingProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdown-policy': {
      id: '/breakdown-policy'
      path: '/breakdown-policy'
      fullPath: '/breakdown-policy'
      preLoaderRoute: typeof BreakdownPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crysta': {
      id: '/crysta'
      path: '/crysta'
      fullPath: '/crysta'
      preLoaderRoute: typeof CrystaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-info': {
      id: '/travel-info'
      path: '/travel-info'
      fullPath: '/travel-info'
      preLoaderRoute: typeof TravelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleets/': {
      id: '/fleets/'
      path: '/fleets'
      fullPath: '/fleets/'
      preLoaderRoute: typeof FleetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleets/$slug': {
      id: '/fleets/$slug'
      path: '/fleets/$slug'
      fullPath: '/fleets/$slug'
      preLoaderRoute: typeof FleetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  BookingProcedureRoute: BookingProcedureRoute,
  BreakdownPolicyRoute: BreakdownPolicyRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactUsRoute: ContactUsRoute,
  CrystaRoute: CrystaRoute,
  DestinationsRoute: DestinationsRoute,
  ExperiencesRoute: ExperiencesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TravelInfoRoute: TravelInfoRoute,
  AreasSlugRoute: AreasSlugRoute,
  FleetsSlugRoute: FleetsSlugRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
  FleetsIndexRoute: FleetsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
